### ISSUE TITLE
Cannot add custom RUNTIME_STYLES when using amp-img

### ISSUE THREAD

**Issue by NgoTraOtoman** [chasefinch/amp-renderer#7]
I want to add my custom RUNTIME_STYLES CSS to my HTML page when using amp-img.
My backend is Flask so this is my code in the backend.
```
@app.route("/testRenderer")
def testRenderer_page():
    renderer = AMPRenderer(
        runtime_version="002106182132000",
        runtime_styles=""".testRenderer{background-color:red;}body{background-color:pink;}""",
    )
    renderer.should_strip_comments = True
    renderer.should_trim_attributes = True

    return renderer.render(render_template("testRenderer.html"))
```
if my testRenderer.html like this one
```
<!doctype html>
<html ⚡️>

<head>
</head>

<body>
    <div class="testRenderer">testRenderer</div>
    <amp-img src="https://i.ibb.co/N7br0BR/ezgif-com-resize-40.jpg" width="500px" height="500px" layout="fixed">
    </amp-img>
</body>

</html>
```
This is the result
![image](https://user-images.githubusercontent.com/85274343/125802078-c7960a26-306a-459e-bdfe-222617f015ed.png)

if my testRenderer.html like this one
```
<!doctype html>
<html ⚡️>

<head>
    <script async src=https://cdn.ampproject.org/v0.js></script>
</head>

<body>
    <div id="testDiv" class="testClass"></div>
    <div class="testRenderer">testRenderer</div>
    <amp-img src="https://i.ibb.co/N7br0BR/ezgif-com-resize-40.jpg" width="500px" height="500px" layout="fixed">
    </amp-img>
</body>

</html>
```
The result is 
![image](https://user-images.githubusercontent.com/85274343/125802213-f0cce5f8-b93a-4b81-8465-f7132519a565.png)

I want to show the img and also have the pink background (also a red background in div) - I mean my CSS style.

I just found the problem is all about `<script async src=https://cdn.ampproject.org/v0.js></script>`. When it appears in the head tag, content of <style amp-runtime="">...</style> use css of https://cdn.ampproject.org/v0.js and do not use my css, and vice versa.
![image](https://user-images.githubusercontent.com/85274343/125802763-b950b00e-5db3-4452-9ed4-3822fdaa3d60.png)

Thank you for your help

**Comment by chasefinch** [comment]
The `runtime_styles` attribute isn't for custom CSS; It should contain the full, current contents of this file: https://cdn.ampproject.org/v0.css

The reason it's a dynamic attribute is because that file changes slightly with every AMP version released, so you need to periodically update it to the latest contents of that file at the same time as you update `runtime_version`.

Just so you know, it's a long string that basically gets pasted into the python code... this is what it looks like in my primary use case:

<img width="873" alt="Screen Shot 2021-07-15 at 10 16 52 AM" src="https://user-images.githubusercontent.com/1236825/125803565-ff7e216e-6675-42d1-ac79-d4b096d25532.png">

The custom CSS for your AMP page goes directly on the page itself, inside of the `<style amp-custom>` tag. Here are [the docs](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/) on that.

**Comment by NgoTraOtoman** [comment]
Follow your instruction I change my RUNTIME_STYLES like this

**Comment by NgoTraOtoman** [comment]
@chasefinch Follow your instruction I change my RUNTIME_STYLES like this
![image](https://user-images.githubusercontent.com/85274343/125809064-3ac59188-46f1-428e-8f5b-0cf6efd20f53.png)
and the HTML like this 
```
<!doctype html>
<html ⚡️>

<head>
    <style amp-custom>
        .testRenderer {
            background-color: red;
        }

        body {
            background-color: pink;
        }
    </style>
</head>

<body>
    <div id="testDiv" class="testClass"></div>
    <div class="testRenderer">testRenderer</div>
    <amp-img src="https://i.ibb.co/N7br0BR/ezgif-com-resize-40.jpg" width="500px" height="500px" layout="fixed">
    </amp-img>
</body>

</html> #
```
But the result is like this 
![image](https://user-images.githubusercontent.com/85274343/125809244-fb34a100-758a-447e-abaf-dd837ecced2d.png)
I check that style runtime contains the long string and style custom contains my custom css.
Another question that how do I know the RUNTIME_VERSION? Where I can check it? This problem may happen because I do not know the correct number of RUNTIME_VERSION.

**Comment by chasefinch** [comment]
You do still need the `<style amp-boilerplate>` CSS element in the head. It could be that.

`<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

The runtime version is the number at the top of the source of [https://cdn.ampproject.org/v0.js](https://cdn.ampproject.org/v0.js)

**Comment by NgoTraOtoman** [comment]
@chasefinch I do as you said:
```
<!doctype html>
<html ⚡️>

<head>
    <style amp-boilerplate>
        body {
            -webkit-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
            -moz-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
            -ms-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
            animation: -amp-start 8s steps(1, end) 0s 1 normal both
        }

        @-webkit-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-moz-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-ms-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @-o-keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }

        @keyframes -amp-start {
            from {
                visibility: hidden
            }

            to {
                visibility: visible
            }
        }
    </style><noscript>
        <style amp-boilerplate>
            body {
                -webkit-animation: none;
                -moz-animation: none;
                -ms-animation: none;
                animation: none
            }
        </style>
    </noscript>
    <style amp-custom>
        .testRenderer {
            background-color: red;
        }

        body {
            background-color: pink;
        }
    </style>
</head>

<body>
    <div class="testRenderer">testRendereraa</div>
    <amp-img src="https://i.ibb.co/N7br0BR/ezgif-com-resize-40.jpg" width="500px" height="500px" layout="fixed">
    </amp-img>
</body>

</html>
```
but the result is the same (no image).
I found amp-renderer/tests/spec/boilerplate_then_noscript_removed/ test folder in the repo. Does this test remove the style amp-boilerplare and also noscript? Because I saw that it remove in my case
![image](https://user-images.githubusercontent.com/85274343/125815124-8b52a0a3-8dd9-4f49-8b50-1a877993a1c1.png)

**Comment by chasefinch** [comment]
It does indeed remove the amp-boilerplate, including the noscript part.

From your screenshot it looks like there is something collapsed inside the <amp-img> tag. Could that be the rendered <img>?

**Comment by NgoTraOtoman** [comment]
There are nothing in amp-img (that why it does not show up)
![image](https://user-images.githubusercontent.com/85274343/125823408-d110df01-23f8-40ff-8050-fd67118afa4a.png)

**Comment by chasefinch** [comment]
Ok I see. The `style="width:500px;height:500px;" is the part that the amp-renderer injects. The img tag itself is still injected by the amp runtime; You do still need the `<script async src=https://cdn.ampproject.org/v0.js></script>` in the head of the document. The goal of "prerendering" an `amp-img` is to apply the fixed size the DOM element to avoid layout shift, but not to inject the img tag.

You can actually have the amp-renderer insert the `<img>` tag by adding the attribute `data-hero` to the `<amp-img>` tag, but that doesn't replace the need for including the javascript. `data-hero` is meant to be used by only one or two images which are above the fold for an extra performance boost.

**Comment by NgoTraOtoman** [comment]
@chasefinch I did add the attribute `data-hero` to the `<amp-img>` without add `<script async src=https://cdn.ampproject.org/v0.js></script>` in the head tag and everything seem to work well. But it takes more time to load an image and also loading time of the page is longer.

If I add `<script async src=https://cdn.ampproject.org/v0.js></script>` in the head tag, do I need to keep the long string in RUNTIME_STYLES or just leaves it blank (RUNTIME_STYLES="")?

I want to increase the loading time of my page and optimize the HTML file. Can you give me any advise?

**Comment by chasefinch** [comment]
As I mentioned, the `data-hero` attribute is not meant to replace the script, and the fact that it does indeed show the image is just coincidence. `data-hero` is merely an optional performance optimization for up to two images which appear above the fold.

The script is necessary for any AMP page to function. You do still need to keep the runtime styles, also.
